### PR TITLE
Fix race between k8s and provider when deleting pod

### LINKED ISSUE #867: Pod recreated during pod.DeletionGracePeriodSeconds will be forcibly deleted
### steps to reproduct it:
1. Run `kubectl delete po testpod` (pod.DeletionGracePeriodSeconds=30s), [these](https://github.com/virtual-kubelet/virtual-kubelet/blob/5a39c167a67dfc636325f2bc07aac96b5f5157da/node/podcontroller.go#L484) code were called to guarantee it would be deleted in the provider and Kubernetes.
```go
	// Check whether the pod has been marked for deletion.
	// If it does, guarantee it is deleted in the provider and Kubernetes.
	if pod.DeletionTimestamp != nil {
		log.G(ctx).Debug("Deleting pod in provider")
		if err := pc.deletePod(ctx, pod); errdefs.IsNotFound(err) {
			log.G(ctx).Debug("Pod not found in provider")
		} else if err != nil {
			err := pkgerrors.Wrapf(err, "failed to delete pod %q in the provider", loggablePodName(pod))
			span.SetStatus(err)
			return err
		}

		pc.deletionQ.AddAfter(key, time.Second*time.Duration(*pod.DeletionGracePeriodSeconds))
		return nil
	}
```
2. In my case, the old pod was successfully deleted in 5s (shorter than pod.DeletionGracePeriodSeconds)
3. Run `kubectl apply -f testpod.yaml`  immediately, the new pod with the same name and namespace was created
4. After the time of pod.DeletionGracePeriodSeconds, [deletePodHandler](https://github.com/virtual-kubelet/virtual-kubelet/blob/5a39c167a67dfc636325f2bc07aac96b5f5157da/node/pod.go#L342) will check whether the pod has been deleted in the kubernetes. However, it got the new one (as the name and namespaces are same).  It will delete the pod directly without any other checks.  
```go
	// If the pod has been deleted from API server, we don't need to do anything.
	k8sPod, err := pc.podsLister.Pods(namespace).Get(name)
	if errors.IsNotFound(err) {
		return nil
	}
	if err != nil {
		span.SetStatus(err)
		return err
	}

	if running(&k8sPod.Status) {
		log.G(ctx).Error("Force deleting pod in running state")
	}

	// We don't check with the provider before doing this delete. At this point, even if an outstanding pod status update
	// was in progress,
	err = pc.client.Pods(namespace).Delete(ctx, name, *metav1.NewDeleteOptions(0))
	if errors.IsNotFound(err) {
		return nil
	}
	if err != nil {
		span.SetStatus(err)
		return err
	}
```

As a result， the new pod was deleted unexpectedly.

### LINKED ISSUE #907: Race issue between k8s and provider when deleting pod
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)

k8s

Version (e.g. 0.1, 0.2-beta)

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

Install Method (e.g. Helm Chart, )

### Issue Details
1. Create Pod
2. Delete pod and re-create the pod in k8s. 
3. pod re-created may be deleted again by provider

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/node/pod.go#L384

### PR DESCRIPTION
**Pull request by cwdsuzhou**
Fixes #867 
Fixes #907

### CODE REVIEW

File: node/pod.go [hunk 1]
```diff
@@ -374,7 +379,10 @@ func (pc *PodController) deletePodHandler(ctx context.Context, key string) (retE
 		span.SetStatus(err)
 		return err
 	}
-
+	if string(k8sPod.UID) != uid {
+		log.G(ctx).Errorf("Pod uid: %v, desired uid: %v", k8sPod.UID, uid)
```
Comment (sargun) [inline node/pod.go:383]: Please use withField

Comment (sargun) [reply node/pod.go:383]: Also, make this error message "make more sense" - something like:

log.G(ctx).WithField("k8sPodUID", k8sPod.UID).WithField("uid", uid).Warn("Not deleting pod because remote pod has different UID")

File: node/pod.go [hunk 2]
```diff
@@ -344,7 +345,11 @@ func (pc *PodController) deletePodHandler(ctx context.Context, key string) (retE
 	ctx, span := trace.StartSpan(ctx, "processDeletionReconcilationWorkItem")
 	defer span.End()
 
-	namespace, name, err := cache.SplitMetaNamespaceKey(key)
+	idx := strings.LastIndex(key, "-")
```
Comment (sargun) [inline node/pod.go:348]: I do not recommend we change out the key format. That seems like it could quickly, and easily generate confusion.

**Review by sargun — CHANGES_REQUESTED** [review]
I believe this is the wrong approach because it still allows for a race The deletePodHandler can read from the knownPods map, and get the pod UID / (and resource version?) from there. 

In that, it can populate DeleteField's Precondition:

https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#DeleteOptions

In that, you can specify a UID precondition:

https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#Preconditions

Thanks for addressing this work!

**Comment by sargun** [comment]
P.P.S.

There is a slight problem introduced, in that in AddFunc we get a duplicate pod in known pods potentially because a pod with the same key has been added. Perhaps we introduce another syncMap of deleting pods that things are transitioned to? Even at that, I can imagine this being confusing.

File: node/pod.go (hunk 2 above)
Comment (cwdsuzhou) [reply node/pod.go]: have changed "-" to "/"

**Comment by cwdsuzhou** [comment]
> I believe this is the wrong approach because it still allows for a race The deletePodHandler can read from the knownPods map, and get the pod UID / (and resource version?) from there.
> 
> In that, it can populate DeleteField's Precondition:
> 
> https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#DeleteOptions
> 
> In that, you can specify a UID precondition:
> 
> https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#Preconditions
> 
> Thanks for addressing this work!

I do not think race still exists. But use `Preconditions` may be better

File: node/pod.go (hunk 1 above)
Comment (cwdsuzhou) [reply node/pod.go]: done

File: node/pod.go [hunk 3]
```diff
@@ -344,7 +345,10 @@ func (pc *PodController) deletePodHandler(ctx context.Context, key string) (retE
 	ctx, span := trace.StartSpan(ctx, "processDeletionReconcilationWorkItem")
 	defer span.End()
 
-	namespace, name, err := cache.SplitMetaNamespaceKey(key)
+	idx := strings.LastIndex(key, "/")
```
Comment (sargun) [inline node/pod.go:348]: I'm reluctant to mess with this in any way. I yield to @cpuguy83 if you want to pass messages through the queue like this.

File: node/pod.go [hunk 4]
```diff
@@ -374,17 +378,25 @@ func (pc *PodController) deletePodHandler(ctx context.Context, key string) (retE
 		span.SetStatus(err)
 		return err
 	}
-
+	if string(k8sPod.UID) != uid {
```
Comment (sargun) [inline node/pod.go:381]: Why not just rely on the precondition check?

Comment (cwdsuzhou) [reply node/pod.go:381]: If we can not pass this check, we do not need send a request to k8s again.

File: node/podcontroller.go [hunk 5]
```diff
@@ -313,10 +313,11 @@ func (pc *PodController) Run(ctx context.Context, podSyncWorkers int) (retErr er
 			if key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(pod); err != nil {
 				log.G(ctx).Error(err)
 			} else {
+				k8sPod := pod.(*corev1.Pod)
 				pc.knownPods.Delete(key)
 				pc.k8sQ.AddRateLimited(key)
 				// If this pod was in the deletion queue, forget about it
-				pc.deletionQ.Forget(key)
+				pc.deletionQ.Forget(fmt.Sprintf("%v/%v", key, k8sPod.UID))
```
Comment (sargun) [inline node/podcontroller.go:320]: Maybe a different approach to stuffing the key in here:

1. You add the pod to the deletionQ
2. The pod gets popped off the deletionQ
3. When the pod gets popped off the deletionQ, you load it from knownPods
4. You check pod.DeletionTimestamp != nil && !running(&pod.Status) -- Maybe even DeletionTimestamp >= time.Now()?

**Comment by sargun** [comment]
@cwdsuzhou I made a comment on how I think this can be simpler.

File: node/podcontroller.go (hunk 5 above)
Comment (cwdsuzhou) [reply node/podcontroller.go:323]: Thanks for you suggestions!

But I think pod UID is the real points we concerns. If we did not check uid, we may incorrectly delete a pod.

**Comment by cwdsuzhou** [comment]
@cpuguy83  PTAL thanks

File: node/pod.go (hunk 4 above)
Comment (pires) [reply node/pod.go:404]: The request is not send to API server directly but instead to the local cache which IIRC will validate the `deleteOptions`.

**Review by pires — CHANGES_REQUESTED** [review]
Please, implement at least one e2e test that proves this fix.

**Comment by cwdsuzhou** [comment]
> > Please, implement at least one e2e test that proves this fix.
> 
> Thanks! IMO this may be hard to add e2e tests since there are chances that the pod controller works correctly.
> 
> Will have a try

Add some unit tests

File: node/pod.go (hunk 4 above)
Comment (sargun) [reply node/pod.go:404]: @pires Are there any docs about that? Can't that lead to a different kind of race?

File: node/pod.go [hunk 6]
```diff
@@ -397,15 +401,25 @@ func (pc *PodController) deletePodsFromKubernetesHandler(ctx context.Context, ke
...
 	}
 
 	// We don't check with the provider before doing this delete. At this point, even if an outstanding pod status update
 	// was in progress,
-	err = pc.client.Pods(namespace).Delete(ctx, name, *metav1.NewDeleteOptions(0))
+	deleteOptions := metav1.NewDeleteOptions(0)
+	deleteOptions.Preconditions = metav1.NewUIDPreconditions(uid)
+	err = pc.client.Pods(namespace).Delete(ctx, name, *deleteOptions)
 	if errors.IsNotFound(err) {
+		log.G(ctx).Warnf("Not deleting pod because %v", err)
```
Comment (sargun) [inline node/pod.go:418]: WithError?

File: node/pod_test.go [hunk 7]
```diff
@@ -20,16 +20,20 @@ import (
...
 	corev1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/api/errors"
 	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/runtime/schema"
 	kubeinformers "k8s.io/client-go/informers"
 	"k8s.io/client-go/kubernetes/fake"
+	core "k8s.io/client-go/testing"
 	"k8s.io/client-go/util/workqueue"
+
```
Comment (sargun) [inline node/pod_test.go:35]: Please drop this new line

**Review by sargun — COMMENTED** [review]
Other than the mechanism of adding metadata to the queue item to dedupe it, this looks okay to me apart from some minor nits. I yield to @pires or @cpuguy83 since they originally built the WQ based mechanism

**Comment by cwdsuzhou** [comment]
@sargun PR addressed

**Comment by sargun** [comment]
@cpuguy83 ^

**Comment by pires** [comment]
I plan to review this over the weekend.

**Comment by pires** [comment]
I didn't get the chance to review, I'm sorry. Will try again during the week or weekend.

**Comment by cwdsuzhou** [comment]
> I didn't get the chance to review, I'm sorry. Will try again during the week or weekend.

Hi @pires  could you help review this PR this week?  thanks!

File: node/pod.go (hunk 4 above)
Comment (pires) [reply node/pod.go:404]: I just realized we're calling the `client` directly here, so it's a REST call and no cache is involved.

Comment (pires) [reply node/pod.go:404]: I think it's fine to send a request to Kubernetes API as this is a corner case and after the key is processed it shouldn't show up again.

File: node/pod.go [hunk 8]
```diff
@@ -397,15 +401,25 @@ func (pc *PodController) deletePodsFromKubernetesHandler(ctx context.Context, ke
...
-	err = pc.client.Pods(namespace).Delete(ctx, name, *metav1.NewDeleteOptions(0))
+	deleteOptions := metav1.NewDeleteOptions(0)
+	deleteOptions.Preconditions = metav1.NewUIDPreconditions(uid)
+	err = pc.client.Pods(namespace).Delete(ctx, name, *deleteOptions)
 	if errors.IsNotFound(err) {
+		log.G(ctx).WithError(err).Error("Not deleting pod")
+		return nil
+	}
+	if errors.IsConflict(err) {
+		log.G(ctx).WithError(err).Error("Not deleting pod")
```
Comment (pires) [inline node/pod.go:422]: I'd use a .`Warn` stating why the conflict is happening, eg _there was a conflict, maybe trying to delete a Pod that has been recreated_.

**Review by pires — CHANGES_REQUESTED** [review]
I agree with @sargun initial review and I ask for the removal of code that injects/reads Pod UID into queue keys and instead simply pass the appropriate `DeleteOptions` with a `Precondition` that ensures the Pod UID is set.

File: node/pod.go (hunk 3 above)
Comment (pires) [reply node/pod.go:371]: That said, the Pod UID must come from somewhere and I'm not sure where because:
- `knownPods` shouldn't have the _old_ Pod around
- there's no way to access the provider's `deletedPods` map

So, ignore my last comment.

**Review by pires — APPROVED** [review]
I don't like most of this change but it does seems to fix this particular issue, and, right now, I can't think of any solution that doesn't require some deeper thinking into how we handle Pod events. And I do think that it will take some time to do that, including coming up with a design that covers as many scenarios as we can come up with, before any execution is taken on.

**Comment by pires** [comment]
@sargun @cpuguy83 is there something you want to add?

File: node/pod.go (hunk 8 above)
Comment (cwdsuzhou) [reply node/pod.go]: done, log update

**Comment by cwdsuzhou** [comment]
> I don't like most of this change but it does seems to fix this particular issue, and, right now, I can't think of any solution that doesn't require some deeper thinking into how we handle Pod events. And I do think that it will take some time to do that, including coming up with a design that covers as many scenarios as we can come up with, before any execution is taken on.

Thanks,  this is not the best solution, but this can solve the issue without changing the vk designation too much.

**Comment by cwdsuzhou** [comment]
@sargun @pires @cpuguy83 
do you have any other suggestions ? or could you help approve this PR?

Thanks!

**Comment by pires** [comment]
@sargun implicitly LGTM'ed and I have done it explicitly so I'm merging.
