### PR TITLE
Do not close pod sync, use context cancel instead.

### LINKED ISSUE #401: panic on exit due to send on closed channel
This happens if there is an inflight send when VK is shutting down.

```
panic: send on closed channel [recovered]
	panic: send on closed channel [recovered]
	panic: send on closed channel

goroutine 1 [running]:
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/cpuguy83/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x213d2a0, 0x251d0f0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/cpuguy83/go/src/github.com/virtual-kubelet/virtual-kubelet/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x213d2a0, 0x251d0f0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).onAddPod(0xc000084d20, 0x253d2e0, 0xc000768120, 0x2300840, 0xc0007e6e00)
	/Users/cpuguy83/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:46 +0x337
github.com/virtual-kubelet/virtual-kubelet/vkubelet.(*Server).watchForPodEvent.func3(0x2300840, 0xc0007e6e00)
	/Users/cpuguy83/go/src/github.com/virtual-kubelet/virtual-kubelet/vkubelet/pod.go:287 +0x50
```

### PR DESCRIPTION
**Pull request by cpuguy83**
Closing the channel is racey and can lead to a panic on exit.
Instead rely on context cancellation to know if workers should exit.

Fixes #401

### CODE REVIEW

File: vkubelet/pod.go [hunk 1]
```diff
@@ -217,6 +239,13 @@ func (s *Server) updatePodStatuses(ctx context.Context) {
 	span.AddAttributes(trace.Int64Attribute("nPods", int64(len(pods))))
 
 	for _, pod := range pods {
+		select {
```
Comment (robbiezhang) [inline vkubelet/pod.go]: check it here?
https://github.com/virtual-kubelet/virtual-kubelet/blob/2743c07222211bfc5bd855b0e4b4732dc38f638d/vkubelet/vkubelet.go#L108

Comment (cpuguy83) [reply vkubelet/pod.go]: Fixed
